name: Publish to Maven Central

# create a new release on GitHub to trigger this workflow
on:
  release:
    types: [ created ]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      MAVEN_CENTRAL_USERNAME: ${{ secrets.MAVEN_CENTRAL_USERNAME }} # Maven Central username
      MAVEN_CENTRAL_PASSWORD: ${{ secrets.MAVEN_CENTRAL_PASSWORD }} # Maven Central password
      GPG_PRIVATE_KEY: ${{ secrets.GPG_PRIVATE_KEY }} # GPG private key  -----BEGIN PGP PRIVATE KEY BLOCK----- XXXXXXX  -----END PGP PRIVATE KEY BLOCK-----
      GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }} # GPG passphrase

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # Get the release title from the GitHub release
      - name: Get release title
        id: release_title
        run: echo "::set-output name=title::${{ github.event.release.name }}"

      - name: Version properties file update
        uses: dschanoeh/change-property@v1
        with:
          file: version.properties
          property: ads
          value: ${{ steps.release_title.outputs.title }}

      - name: Version properties file update
        uses: dschanoeh/change-property@v1
        with:
          file: version.properties
          property: core
          value: ${{ steps.release_title.outputs.title }}

      - name: Version properties file update
        uses: dschanoeh/change-property@v1
        with:
          file: version.properties
          property: firebase
          value: ${{ steps.release_title.outputs.title }}

      - name: Version properties file update
        uses: dschanoeh/change-property@v1
        with:
          file: version.properties
          property: iot
          value: ${{ steps.release_title.outputs.title }}

      - name: Version properties file read
        run: |
          echo "Version: $(cat version.properties)"

      # Java 11 is required to build the project
      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
          gpg-private-key: ${{ secrets.GPG_PRIVATE_KEY }}
          gpg-passphrase: ${{ secrets.GPG_PASSPHRASE }}

      - name: Build with Gradle
        run: gradle build

      # Publish the project to Maven Central
      - name: Publish to GitHub Packages
        run: gradle publish
        env:
          USERNAME: ${{ github.actor }}
          PASSWORD: ${{ secrets.GITHUB_TOKEN }}