name: Publish
on:
  push:
    branches: [ "master" ]
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Update version.properties
        id: update_version
        run: |
          CURRENT_VERSION=$(grep -oP '(?<=ads=).*' version.properties)
          MAJOR=$(echo $CURRENT_VERSION | cut -d'.' -f1)
          MINOR=$(echo $CURRENT_VERSION | cut -d'.' -f2)
          PATCH=$(echo $CURRENT_VERSION | cut -d'.' -f3)
          NEW_PATCH=$((PATCH + 1))
          NEW_VERSION="$MAJOR.$MINOR.$NEW_PATCH"
          sed -i "s/ads=$CURRENT_VERSION/ads=$NEW_VERSION/" version.properties
          sed -i "s/core=$CURRENT_VERSION/core=$NEW_VERSION/" version.properties
          sed -i "s/firebase=$CURRENT_VERSION/firebase=$NEW_VERSION/" version.properties
          sed -i "s/iot=$CURRENT_VERSION/iot=$NEW_VERSION/" version.properties
          echo "::set-output name=new_version::$NEW_VERSION"
      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'zulu'
          cache: 'gradle'
      - name: Change wrapper permissions
        run: chmod +x ./gradlew
      - name: Build gradle project
        run: ./gradlew build
        
      - name: Build with Gradle
        uses: gradle/gradle-build-action@v2
        with:
          arguments: publish
      - name: Commit version changes
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
          git add version.properties
          git commit -m "Bump version to ${{ steps.update_version.outputs.new_version }}"
          git push
